receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

  syslog:
    tcp:
      listen_address: "0.0.0.0:514"  # Listening on TCP port 514 for Syslog
    protocol: rfc5424  # RFC5424 format
    operators:
      - type: syslog_parser
        protocol: rfc5424
    #     parse_from: body          # Parse the body of the Syslog message
    #     parse_to: attributes     # Store parsed information as attributes
    #     preserve_to: attributes.original_message  # Preserve the original message

exporters:
  debug:
    verbosity: detailed  # Detailed logging for debugging

processors:
  batch:
    timeout: 2s
    send_batch_size: 1024

service:
  pipelines:
    logs:
      receivers: [syslog, otlp]  # Receiver to collect Syslog logs
      processors: [batch]   # Optional: Batch processor
      exporters: [debug]    # Send to debug exporter

    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug]
    
